Repository jose-almir/goodpay, pull requests merged in 2022-10, with the labels that each got.

#50 task: módulo de execução de login
  index.html
  js/index.js
  js/moduloDados.js
Labels: enhancement

#51 Ajustes finais para sprint 04.10
  components/.gitignore
Labels: enhancement

#53 Upload rodapé
  css/styles.css
  index.html
Labels: enhancement

#54 Nav bar
  components/.gitignore
  components/css/stylesNavBar.css
  components/navBar.html
  img/usuario/usuarioLogado.jpeg
Labels: enhancement

#55 Adição de um teste de cálculo para verificação de robôs
  index.html
  js/index.js
Labels: enhancement

#56 Montagem do sistema de erros do login e adição ao menu #31
  index.html
Labels: enhancement

#57 pagfaq
  css/styles.css
  faq.html
Labels: enhancement

#60 Enviando o toast de serviços de localização
  index.html
  js/index.js
Labels: enhancement

#62 Pagina colaborador
  css/stylesCadastroColaborador.css
  js/cadastroColaborador.js
  js/index.js
  paginaCadastroColaborador.html
Labels: enhancement

#63 criação página recupração de senha
  css/recuperacaoDeSenha.css
  index.html
  js/index.js
  recuperacaoDeSenha.html
Labels: enhancement

#69 página da SoulCode
  css/soulcode.css
  img/fundadores.png
  img/logo/light-logo.png
  img/logo/soulcodeicon.png
  img/soulcode-quadrado.jpg
  img/techforgood.jpg
  soulcode.html
Labels: enhancement

#83 Cadastro
  cadastro.html
  css/cadastrostyles.css
  js/cadastro.js
Labels: enhancement

#84 Pagina sorteio
  css/sorteio.css
  js/sorteio.js
  sorteio.html
Labels: enhancement

#85 Update libras
  cadastro.html
  faq.html
  index.html
  mapadosite.html
  paginaCadastroColaborador.html
  recuperacaoDeSenha.html
  sobrenos.html
  soulcode.html
Labels: enhancement

#86 Parceiros
  components/css/stylesNavBar.css
  components/navBar.html
  css/styles.css
  img/banner/BannerGoogleCloud.jpeg
  img/banner/BannerPagSeguro.jpeg
  img/banner/BannerTNT.jpeg
  img/logo/logoCufa.jpeg
  img/logo/logoFalcao.jpeg
  img/logo/logoSalesForces.jpeg
  img/logo/logoServiceNow.jpeg
  index.html
  parceiros.html
Labels: bug, enhancement

#87 subindo as alterações dos modais de promoção
  css/styles.css
  index.html
  js/index.js
Labels: enhancement

#88 Feat/popup
  css/styles.css
  js/popup-conexao.js
  sobrenos.html
Labels: enhancement

#89 Página App.html
  app.html
  css/app.css
  css/recuperacaoDeSenha.css
Labels: enhancement

#95 Update index.js
  js/index.js
Labels: bug

#98 Promocao
  cadastro.html
Labels: enhancement

#101 Criação da página de assinaturas
  assinatura.html
  css/assinatura.css
  js/index.js
Labels: enhancement

#102 Adição da página regra de 3
  css/regrade3.css
  js/regrade3.js
  regrade3.html
Labels: enhancement

#103 implementar blog com cards no GoodPay
  blogCards.html
  css/styles.css
  img/img-blog/img1.png
  img/img-blog/img4.png
  img/img-blog/img5.jpg
  img/img-blog/img6.png
  img/img-blog/img7.png
  img/img-blog/img8.png
Labels: enhancement

#104 Task 37
  css/devTeam.css
  devTeam.html
  img/icones/logo-github.png
Labels: enhancement

#105 Calculadora de Juros Composto
  calculadoraJurosComposto.html
  css/calculadorajuroscomposto.css
  js/calculadoraJurosComposto.js
Labels: enhancement

#107 Página de perfil do usuário
  css/perfildousuario.css
  img/cartãoGoodpay.jpeg
  perfildousuario.html
Labels: enhancement

#108 criação modal e correção de titulo
  css/recuperacaoDeSenha.css
  recuperacaoDeSenha.html
Labels: enhancement

#109 Implementação da página de Objetivos Financeiros
  css/financeiros.css
  financeiros.html
  js/financeiros.js
Labels: enhancement

#110 subindo a calculadora de FGTS
  calculadora-fgts.html
  css/styles.css
  js/calculadora.js
Labels: enhancement

#112 Criacao pagina tabela ICMS
  css/tabela.css
  tabela.html
Labels: enhancement

#113 responsividadeapp
  app.html
  css/app.css
Labels: enhancement

#114 Upload Contador de dias
  contagemDeDias.html
  css/styles.css
  index.html
  js/contagemDias.js
Labels: enhancement

#115 Criação da página de administração #39
  administracao.html
  css/administracao.css
  js/administracao.js
  js/moduloDados.js
Labels: enhancement

#116 Login social
  css/loginSocial.css
  img/icones/facebook.png
  img/icones/github.png
  img/icones/google.png
  img/icones/instagram.png
  img/icones/linkedin.png
  img/icones/logo-github.png
  loginSocial.html
Labels: enhancement

#118 Correção de ortografia, inserção de navbar e logo
  css/recuperacaoDeSenha.css
  recuperacaoDeSenha.html
Labels: enhancement

#119 Feat/aprimorar seo
  app.html
  index.html
  js/meta-tag.js
  metas.html
  navBar.html
  sobrenos.html
Labels: enhancement

#121 protótipo página eBank
  css/styleEbank.css
  paginaEbank.html
Labels: enhancement
